Proekt_cafe_1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from account.views import registration_view, login_view, logout_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('managers/', include('manager.urls', namespace='manager'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_page/urls.py
from django.urls import path

from django.conf.urls.static import settings
from django.conf.urls.static import static

from .views import main_page, render_typography_page, about_new

app_name = 'main_page'

urlpatterns = [
    path('', main_page, name='main_page_view'),
    path('typography/', render_typography_page, name='typography_view'),
    path('about/', about_new, name='about_view'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservations_list'),
]

account/models.py
from django.db import models

# Create your models here.

main_page/models.py
from django.db import models
from uuid import uuid4
from os import path
from django.core.validators import RegexValidator


class Category(models.Model):
    name = models.CharField(max_length=40, unique=False, db_index=True)
    is_visible = models.BooleanField(default=True)
    position = models.PositiveSmallIntegerField(unique=True)

    def __str__(self):
        return f'{self.name}: {self.position}'

    class Meta:
        ordering = ('position', )


class Dish(models.Model):

    def get_file_name(self, filename: str):
        ext = filename.strip().split('.')[-1]
        filename = f'{uuid4()}.{ext}'
        return path.join('images/dishes', filename)

    name = models.CharField(max_length=50, unique=True, db_index=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    ingredients = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    desc = models.TextField(max_length=500, blank=True)
    is_visible = models.BooleanField(default=True)
    featured_offers = models.BooleanField(default=False)
    position = models.PositiveSmallIntegerField()
    photo = models.ImageField(upload_to=get_file_name)

    def __str__(self):
        return f'{self.name}: {self.price}'


class UserReservation(models.Model):
    mobile_regex = RegexValidator(regex=r'^(\d{3}[- .]?){2}\d{4}$', message='Phone in format xxx xxx xxxx')
    name = models.CharField(max_length=50, unique=True, db_index=True)
    phone = models.CharField(max_length=15, validators=[mobile_regex])
    persons = models.PositiveSmallIntegerField()
    message = models.TextField(max_length=500, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_processed = models.BooleanField(default=False)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return f'{self.name}, {self.phone}: {self.message[:30]}'

account/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user or not user.check_password(password):
                raise forms.ValidationError('Неверный пароль или логин')
        return super().clean()


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username',)

    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_password2(self, *args, **kwargs):
        data = self.cleaned_data
        if data['password'] == data['password2']:
            return data['password2']
        return forms.ValidationError('Проли не совпадают!')

main_page/forms.py
from django import forms
from .models import UserReservation


class UserReservationForm(forms.ModelForm):
    name = forms.CharField(max_length=50,
                           widget=forms.TextInput(attrs={
                               'type': "text",
                               'name': "name",
                               'class': "form-input form-control-has-validation",
                               'id': "name",
                               'placeholder': "Your Name",
                               'data-rule': "minlen:4",
                               'data-msg': "Please enter at least 4 chars"
                           }))
    phone = forms.CharField(max_length=15,
                            widget=forms.TextInput(
                                attrs={'type': 'text', 'name': 'phone', 'id': 'phone', 'class': 'form-input form-control-has-validation',
                                       'placeholder': 'Телефон', 'required': 'required',
                                       'data-rule': 'minlen:4', 'data-msg': 'Please enter at least 4 chars'}))
    persons = forms.IntegerField(widget=forms.NumberInput(attrs={
        'type': "number",
        'class': "form-input form-control-has-validation",
        'name': "people",
        'id': "people",
        'placeholder': "# of people",
        'data-rule': "minlen:1",
        'data-msg': "Please enter at least 1 chars"}))

    message = forms.CharField(max_length=400,
                              widget=forms.Textarea(
                                  attrs={'type': 'message', 'name': 'message', 'class': 'form-input form-control-has-validation',
                                         'rows': '5', 'placeholder': 'Сообщение', 'required': 'required'}))

    class Meta:
        model = UserReservation
        fields = ('name', 'phone', 'persons', 'message')

account/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegistrationForm
from django.contrib.auth import authenticate, login, logout


def registration_view(request):
    form = RegistrationForm(request.POST or None)

    if form.is_valid():
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data['password'])
        new_user.save()
        return render(request, 'registration_done.html', context={'user': new_user})
    return render(request, 'registration.html', context={'form': form})


def login_view(request):
    form = LoginForm(request.POST or None)
    next_get = request.GET.get('next')

    if form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username.strip(), password=password.strip())
        login(request, user)
        next_post = request.POST.get('next')
        return redirect(next_get or next_post or '/')
    return render(request, 'login.html', context={'form': form})


def logout_view(request):
    logout(request)
    return redirect('/')

main_page/views.py
from django.shortcuts import render
from .models import Category, Dish


def main_page(request):
    categories = Category.objects.filter(is_visible=True).order_by('position')
    dishes = Dish.objects.filter(is_visible=True).order_by('position')

    return render(request, 'main.html', context={'categories': categories, 'dishes': dishes})


def render_typography_page(request):
    return render(request, 'typography.html', context={})


def about_new(request):
    return render(request, 'about.html', context={})

manager/views.py
from django.shortcuts import render, redirect

from main_page.forms import UserReservationForm
from main_page.models import UserReservation


def reservation_list(request):
    if request.method == 'POST':
        reservation = UserReservationForm(request.POST)
        if reservation.is_valid():
            reservation.save()
            return redirect('/')
    else:
        reservation = UserReservationForm()

    lst = UserReservation.objects.filter(is_processed=False)
    return render(request, 'reservation_list.html', context={'lst': lst, 'reservation': reservation})

account/templates/login.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <section class="parallax-container overlay-1" style="min-height: 300px;"
             data-parallax-img="{% static 'images/breadcrumbs.jpg' %}">
        <div class="material-parallax parallax">
            <img src="{% static 'images/breadcrumbs.jpg' %} " alt=""
                 style="transform: translate3d(-50%, 131px, 0px); display: block;">
        </div>
        <div class="container">
            <div class="section-title text-center">
                <h3>Войти</h3>
            </div>
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-md-6">
                        <form action="" method="post" style="margin-top: 100px;">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Войти">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

account/templates/registration.html
{% extends 'index.html' %}

{% block content %}
    <section class="section section-lg bg-gray-1 text-center">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-md-9 col-lg-7">
                    <div class="row">
                        <div class="col-md-6">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div class="row justify-content-center">
                                    <button class="button button-block button-lg button-primary" type="submit">
                                        Зарегистрироваться
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

account/templates/registration_done.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <section class="parallax-container overlay-1" style="min-height: 300px;"  data-parallax-img="{% static 'images/breadcrumbs.jpg' %}">
        <div class="material-parallax parallax">
            <img src="{% static 'images/breadcrumbs.jpg' %} " alt=""
                 style="transform: translate3d(-50%, 131px, 0px); display: block;">
        </div>
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-md-6">
                        <h1 class="display-4">Привет, {{ new_user.username }}</h1>
                        <p>Вы зарегистрированы в системе. </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

main_page/templates/typography.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <section class="parallax-container overlay-1" data-parallax-img="{% static 'images/my_images/castellamare-restaurant-8-1920x570.jpg' %}">
        <div class="material-parallax parallax"><img src="{% static 'images/my_images/castellamare-restaurant-8-1920x570.jpg' %}" alt=""
                                                     style="display: block; transform: translate3d(-50%, 165px, 0px);">
        </div>
        <div class="parallax-content breadcrumbs-custom context-dark">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-9">
                        <h2 class="breadcrumbs-custom-title">Typography</h2>
                        <ul class="breadcrumbs-custom-path">
                            <li><a href="{% url 'main_page:main_page_view' %}">Home</a></li>
                            <li class="active">Typography</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-lg bg-default">
        <div class="container">
            <div class="row row-50 flex-lg-row-reverse justify-content-xl-between">
                <div class="col-xl-4">
                    <div class="block-bordered-left">
                        <div class="row row-40">
                            <div class="col-sm-6 col-xl-12">
                                <h5 class="thin-title">Fonts</h5>
                                <h2 class="heading-font text-accent-3">henric</h2>
                                <h3 class="heading-font font-family-base">Poppins</h3>
                                <h2 class="heading-font text-accent-2">Tuesday </h2>
                            </div>
                            <div class="col-sm-6 col-xl-12">
                                <h5 class="thin-title">Colors</h5>
                                <ul class="list-color">
                                    <li>
                                        <div class="box-color bg-primary"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-pink"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-secondary"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-green"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-secondary-2"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-gray-800"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-gray-400"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-gray-300"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-gray-600"></div>
                                    </li>
                                    <li>
                                        <div class="box-color bg-gray-700"></div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-7">
                    <ul class="list-xxl heading-list">
                        <li>
                            <h1>H1 Heading</h1>
                            <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our
                                website will find exactly what he/she is looking for. With advanced features of
                                activating account and new login widgets, you will definitely have a great experience of
                                using our web page.</p>
                        </li>
                        <li>
                            <h2>H2 Heading</h2>
                            <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our
                                website will find exactly what he/she is looking for. With advanced features of
                                activating account and new login widgets, you will definitely have a great experience of
                                using our web page.</p>
                        </li>
                        <li>
                            <h3>H3 Heading</h3>
                            <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our
                                website will find exactly what he/she is looking for. With advanced features of
                                activating account and new login widgets, you will definitely have a great experience of
                                using our web page.</p>
                        </li>
                        <li>
                            <h4>H4 Heading</h4>
                            <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our
                                website will find exactly what he/she is looking for. With advanced features of
                                activating account and new login widgets, you will definitely have a great experience of
                                using our web page.</p>
                        </li>
                        <li>
                            <h5>H5 Heading</h5>
                            <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our
                                website will find exactly what he/she is looking for. With advanced features of
                                activating account and new login widgets, you will definitely have a great experience of
                                using our web page.</p>
                        </li>
                        <li>
                            <h6>H6 Heading</h6>
                            <p>Welcome to our wonderful world. We sincerely hope that each and every user entering our
                                website will find exactly what he/she is looking for. With advanced features of
                                activating account and new login widgets, you will definitely have a great experience of
                                using our web page.</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

manager/templates/reservation_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <section class="parallax-container overlay-1">
        <div class="parallax-content breadcrumbs-custom context-dark">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-9">
                        <h2 class="breadcrumbs-custom-title">Contacts</h2>
                        <ul class="breadcrumbs-custom-path">
                            <li><a href="{% url 'main_page:main_page_view' %}">Home</a></li>
                            <li class="active">Contacts</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="section section-lg text-center bg-default">
        <div class="container">
            <div class="row row-50">
                <div class="col-md-6 col-lg-4">
                    <div class="box-icon-classic">
                        <div class="box-icon-inner decorate-triangle"><span
                                class="icon-xl linearicons-phone-incoming"></span></div>
                        <div class="box-icon-caption">
                            <h4><a href="tel:#">1-800-123-1234</a></h4>
                            <p>You can call us anytime</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="box-icon-classic">
                        <div class="box-icon-inner decorate-circle"><span class="icon-xl linearicons-map2"></span></div>
                        <div class="box-icon-caption">
                            <h4><a href="javascript:void(0);">51 Francis Street, San Diego, CA 91702 United States</a></h4>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="box-icon-classic">
                        <div class="box-icon-inner decorate-rectangle"><span
                                class="icon-xl linearicons-paper-plane"></span></div>
                        <div class="box-icon-caption">
                            <h4><a href="mailto:#">info@demolink.org</a></h4>
                            <p>Feel free to email us your questions</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="section section-lg bg-gray-1 text-center">
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-md-9 col-lg-7">
                    <h3 id="get-it-touch">Get in Touch</h3>
                    <!-- RD Mailform-->
                    <form method="post" role="form">
                        {% csrf_token %}

                        {% if reservation.errors %}
                            <div class="alert alert-danger">
                                {{ reservation.errors }}
                            </div>
                        {% endif %}

                        <div class="form-wrap">
                            {{ reservation.name }}
                            <div class="validate"></div>
                        </div>
                        <div class="form-wrap">
                            {{ reservation.phone }}
                            <div class="validate"></div>
                        </div>
                        <div class="form-wrap">
                            {{ reservation.persons }}
                            <div class="validate"></div>
                        </div>

                        <div class="form-wrap">
                            {{ reservation.message }}
                            <div class="validate"></div>
                        </div>


                        <div class="row justify-content-center">
                            <div class="col-12 col-sm-7 col-lg-5">
                                <button class="button button-block button-lg button-primary" type="submit">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href={% static "images/favicon.ico" %} type="image/x-icon">
    <link rel="stylesheet" type="text/css"
          href="//fonts.googleapis.com/css?family=Poppins:300,300i,400,500,600,700,800,900,900i%7CPT+Serif:400,700">
    <link rel="stylesheet" href={% static "css/bootstrap.css" %}>
    <link rel="stylesheet" href={% static "css/fonts.css" %}>
    <link rel="stylesheet" href={% static "css/style.css" %}>
    <style>.ie-panel {
        display: none;
        background: #212121;
        padding: 10px 0;
        box-shadow: 3px 3px 5px 0 rgba(0, 0, 0, .3);
        clear: both;
        text-align: center;
        position: relative;
        z-index: 1;
    }

    html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {
        display: block;
    }</style>
</head>
<body>
<div class="preloader">
    <div class="preloader-body">
        <div class="cssload-container">
            <div class="cssload-speeding-wheel"></div>
        </div>
        <p>Loading...</p>
    </div>
</div>
<div class="page">
    <!-- Page Header-->
    <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
            <nav class="rd-navbar rd-navbar-classic" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed"
                 data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed"
                 data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static"
                 data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static"
                 data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px" data-xxl-stick-up-offset="46px"
                 data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
                <div class="rd-navbar-main-outer">
                    <div class="rd-navbar-main">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap">
                                <span></span></button>
                            <!-- RD Navbar Brand-->
                            <div class="rd-navbar-brand"><a href="{% url 'main_page:main_page_view' %}"><img class="brand-logo-light"
                                                                                   alt=""
                                                                                   src={% static 'images/logo-default1-140x57.png' %} alt=""
                                                                                   width="140" height="57"
                                                                                   srcset="{% static 'images/logo-default-280x113.png' %} 2x"/></a>
                            </div>
                        </div>
                        <div class="rd-navbar-main-element">
                            <div class="rd-navbar-nav-wrap">
                                <!-- RD Navbar Nav-->
                                <ul class="rd-navbar-nav">
                                    <li class="rd-nav-item"><a class="rd-nav-link"
                                                                      href="{% url 'main_page:main_page_view' %}">Home</a>
                                    </li>
                                    <li class="rd-nav-item"><a class="rd-nav-link"
                                                               href="{% url 'main_page:about_view' %}">About</a>
                                    </li>
                                    <li class="rd-nav-item"><a class="rd-nav-link"
                                                               href="{% url 'main_page:typography_view' %}">Typography</a>
                                    </li>
                                    <li class="rd-nav-item"><a class="rd-nav-link"
                                                               href="{% url 'manager:reservations_list' %}">Contacts</a>
                                    </li>
                                    {% if user.is_authenticated %}
                                        <li class="rd-nav-item"><a class="rd-nav-link"
                                                                   href="{% url 'logout' %}">Logout</a>
                                        </li>
                                    {% else %}
                                        <li class="rd-nav-item"><a class="rd-nav-link"
                                                                   href="{% url 'login' %}">Login</a>
                                        </li>
                                        <li class="rd-nav-item"><a class="rd-nav-link"
                                                                   href="{% url 'registration' %}">Registration</a>
                                        </li>
                                    {% endif %}
                                </ul>
                                <a class="button button-white button-sm" href="{% url 'manager:reservations_list' %}#get-it-touch">book now</a>
                            </div>
                        </div>
                        <a class="button button-white button-sm" href="{% url 'manager:reservations_list' %}#get-it-touch">book now</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <!-- Swiper-->



    {% block content %}

    {% endblock %}




    <!-- Page Footer-->
    <footer class="section footer-minimal context-dark">
        <div class="container wow-outer">
            <div class="wow fadeIn">
                <div class="row row-60">
                    <div class="col-12"><a href="{% url 'main_page:main_page_view' %}"><img
                            src="{% static 'images/logo-default1-140x57.png' %}" alt="" width="140" height="57"
                            srcset="{% static 'images/logo-default-280x113.png' %} 2x"/></a></div>
                    <div class="col-12">
                        <ul class="footer-minimal-nav">
                            <li><a href="{% url 'manager:reservations_list' %}">Contacts</a></li>
                            <li><a href="{% url 'main_page:about_view' %}">About</a></li>
                        </ul>
                    </div>
                    <div class="col-12">
                        <ul class="social-list">
                            <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-facebook"
                                   href="javascript:void(0);"></a></li>
                            <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-instagram"
                                   href="javascript:void(0);"></a></li>
                            <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-twitter"
                                   href="javascript:void(0);"></a></li>
                            <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-youtube-play"
                                   href="javascript:void(0);"></a></li>
                            <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-pinterest-p"
                                   href="javascript:void(0);"></a></li>
                        </ul>
                    </div>
                </div>
                <p class="rights"><span>&copy;&nbsp; </span><span
                        class="copyright-year"></span><span>&nbsp;</span><span>Pesto</span><span>.&nbsp;</span><span>All Rights Reserved.</span><span>&nbsp;</span><a
                        href="javascript:void(0);">Privacy Policy</a>. Design&nbsp;by&nbsp;<a href="https://www.templatemonster.com">Templatemonster</a>
                </p>
            </div>
        </div>
    </footer>
</div>
<div class="snackbars" id="form-output-global"></div>
<script src={% static "js/core.min.js" %}></script>
<script src={% static "js/script.js" %}></script>
</body>
</html>